query ($page: Int, $perPage: Int, $filter: FilterOption, $start: Date, $end: Date) {
  archive: ArchivePagination (page: $page, perPage: $perPage, filter: $filter, start: $start, end: $end) {
    data {
      _id
      name
      themeName
      address
      detailAddress
      lat
      lng
      openTime {
        hour
        minute
      }
      closeTime {
        hour
        minute
      }
      startDate
      endDate
      artist {
        _id
        name
      }
      group {
        _id
        name
      }
      mainImage {
        _id
        name
        path
      }
      images {
        _id
        name
        path
      }
      organizer
      phoneNumber
      link
    }
    total
  }
}
