query (
  $page: Int
  $perPage: Int
  $filter: FilterOption
  $start: Date
  $end: Date
  $sortOrder: Int
  $sortField: String
) {
  archive: ArchivePagination(
    page: $page
    perPage: $perPage
    filter: $filter
    start: $start
    end: $end
    sortOrder: $sortOrder
    sortField: $sortField
  ) {
    data {
      _id
      name
      themeName
      favorite
      address
      detailAddress
      lat
      lng
      district {
        code
        name
      }
      openTime {
        hour
        minute
      }
      closeTime {
        hour
        minute
      }
      startDate
      endDate
      artist {
        _id
        name
      }
      group {
        _id
        name
      }
      mainImage {
        _id
        name
        path
      }
      images {
        _id
        name
        path
      }
      favoriteGroup {
        _id
      }
      organizer
      phoneNumber
      link
    }
    total
  }
}
