query ($id: ID!) {
  favoriteGroup: FavoriteGroup(id: $id) {
    _id
    title
    color
    archives {
      _id
      name
      themeName
      favorite
      address
      detailAddress
      lat
      lng
    }
  }
}
