query ($page: Int, $perPage: Int, $filter: FilterOption) {
  favoriteGroups: FavoritePagination (page: $page, perPage: $perPage, filter: $filter) {
    data {
      _id
      user {
        name
      }
    }
    total
  }
}
