query FavoritePagination($sortOrder: Int, $page: Int, $perPage: Int, $group: ID, $start: Date, $end: Date) {
  FavoritePagination(sortOrder: $sortOrder, page: $page, perPage: $perPage, group: $group, start: $start, end: $end) {
    data {
      _id
      archive {
        _id
        themeName
        organizer
        favorite
        startDate
        endDate
        group {
          _id
          name
        }
        artist {
          _id
          name
        }
      }
    }
    total
  }
}
