mutation ($token: String!, $provider: String) {
  user: signIn (code: $token, provider: $provider) {
    user {
      _id
      name
      email
      provider
      providerId
      image
    }
    token
  }
}
