mutation ($token: String!, $provider: String) {
  auth: signIn (accessToken: $token, provider: $provider) {
    user {
      _id
      name
      email
      provider
      providerId
      image
      role
    }
    token
  }
}
